### ISSUE TITLE
Inverter does not go below 100 W?

### ISSUE THREAD

**Issue by PepeTheFroggie** [martiby/multiplus2#3]
Ty for your work. Running it on a windows machine. Only change was "port = 'com3'".
The multiplus in inverter mode (charger disabled) does not go below 100W and does not shut off at zero watt?
Can someone confirm?
I have charger disabled because i have no battery yet.

**Comment by martiby** [comment]
I have just tried it. 50W feed in manual mode as a setpoint for the Multiplus. The value is measured with an Eastron SDM120 ( MeterHUB --> Batterie). Should actually work. 

![ess_feed_50w](https://github.com/martiby/multiplus2/assets/59184567/cfba2857-a55f-4749-b7ec-7cef1ba8a99b)
